In [1]:
import pandas as pd

In [6]:
df=pd.read_csv(r"https://docs.google.com/spreadsheets/d/e/2PACX-1vSPVJIoDhupNyUpYD65FSHt6kMmF_KaxE2RD6CV1FOMP4vVw7WfKQMqpqo0ieD9vhMAmYP1NpBmw0od/pub?gid=658985149&single=true&output=csv")
df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df=df.drop_duplicates()
df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
5,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.drop(columns="Unnamed: 3")

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
5,NaN,NaN,2021,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
5,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df["Unnamed: 2"]=df["Unnamed: 2"].str.lstrip("/")
df["Unnamed: 2"]=df["Unnamed: 2"].str.lstrip("...")
df["Unnamed: 2"]=df["Unnamed: 2"].str.rstrip("_")

In [35]:
df["Unnamed: 12"]=df["Unnamed: 12"].str.lstrip("-")

In [47]:
df = df.drop(3)

In [38]:
df = df.drop(1)

In [50]:
df = df.drop(4)
df = df.drop(6)

In [58]:
df = df.drop(df.index[231:274])

In [59]:
df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
7,1,Switzerland,962,84.0,16.5,13.9,"66,933",5,3
8,2,Norway,961,83.2,18.2,13.0,"64,660",6,1
9,3,Iceland,959,82.7,19.2,13.8,"55,782",11,2
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4
11,5,Australia,951,84.5,21.1,12.7,"49,238",18,5
...,...,...,...,...,...,...,...,...,...
241,NaN,k. Estimated using the PPP rate of Spain.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,NaN,l. Based on cross-country regression.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,m. Updated by HDRO based on data from UNESCO I...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,n. Updated by HDRO based on data from Barro an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,NaN,o. Updated by HDRO based on data from CEDLAS a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:

df = df.drop(231)
df = df.drop(232)
df = df.drop(233)
df = df.drop(234)
df = df.drop(235)
df = df.drop(236)
df = df.drop(237)
df = df.drop(238)
df = df.drop(239)
df = df.drop(240)
df = df.drop(241)
df = df.drop(242)
df = df.drop(243)
df = df.drop(244)

df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
7,1,Switzerland,962,84.0,16.5,13.9,"66,933",5,3
8,2,Norway,961,83.2,18.2,13.0,"64,660",6,1
9,3,Iceland,959,82.7,19.2,13.8,"55,782",11,2
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4
11,5,Australia,951,84.5,21.1,12.7,"49,238",18,5
...,...,...,...,...,...,...,...,...,...
221,NaN,Sub-Saharan Africa,547,60.1,10.3,6.0,"3,699",—,—
223,NaN,Least developed countries,540,64.2,10.2,5.2,"2,881",—,—
224,NaN,Small island developing states,730,70.3,12.4,9.1,"16,782",—,—
226,NaN,Organisation for Economic Co-operation and Dev...,899,79.0,16.5,12.3,"45,087",—,—
228,NaN,World,732,71.4,12.8,8.6,"16,752",—,—

In [66]:
df = df.rename(columns={'Back': 'HDI rank', 'Table 1. Human Development Index and its components': 'Country', 'Unnamed: 2': 'Human Development Index (HDI)','Unnamed: 4': 'Life expectancy at birth','Unnamed: 6': 'Expected years of schooling','Unnamed: 8': 'Mean years of schooling','Unnamed: 10': 'Gross national income (GNI) per capita','Unnamed: 12': 'GNI per capita rank minus HDI rank','Unnamed: 14': 'HDI rank 2020'})

In [67]:
df

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020
7,1,Switzerland,962,84.0,16.5,13.9,"66,933",5,3
8,2,Norway,961,83.2,18.2,13.0,"64,660",6,1
9,3,Iceland,959,82.7,19.2,13.8,"55,782",11,2
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4
11,5,Australia,951,84.5,21.1,12.7,"49,238",18,5
...,...,...,...,...,...,...,...,...,...
221,NaN,Sub-Saharan Africa,547,60.1,10.3,6.0,"3,699",—,—
223,NaN,Least developed countries,540,64.2,10.2,5.2,"2,881",—,—
224,NaN,Small island developing states,730,70.3,12.4,9.1,"16,782",—,—
226,NaN,Organisation for Economic Co-operation and Dev...,899,79.0,16.5,12.3,"45,087",—,—
228,NaN,World,732,71.4,12.8,8.6,"16,752",—,—

In [76]:
df["HDI rank"]=df["HDI rank"].str.replace("NaN","")

In [89]:
df.fillna("")

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020
7,1,Switzerland,962,84.0,16.5,13.9,"66,933",5,3
8,2,Norway,961,83.2,18.2,13.0,"64,660",6,1
9,3,Iceland,959,82.7,19.2,13.8,"55,782",11,2
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4
11,5,Australia,951,84.5,21.1,12.7,"49,238",18,5
...,...,...,...,...,...,...,...,...,...
221,,Sub-Saharan Africa,547,60.1,10.3,6.0,"3,699",—,—
223,,Least developed countries,540,64.2,10.2,5.2,"2,881",—,—
224,,Small island developing states,730,70.3,12.4,9.1,"16,782",—,—
226,,Organisation for Economic Co-operation and Dev...,899,79.0,16.5,12.3,"45,087",—,—
228,,World,732,71.4,12.8,8.6,"16,752",—,—

In [104]:
for x in df.index:
  if df.loc[x,"GNI per capita rank minus HDI rank"] == "—":
    df.drop(x,inplace=True)
    df

In [105]:
for x in df.index:
  if df.loc[x,"GNI per capita rank minus HDI rank"] == "..":
    df.drop(x,inplace=True)
    df

In [113]:
for x in df.index:
  if df.loc[x,"GNI per capita rank minus HDI rank"] == "OTHER COUNTRIES OR TERRITORIES":
    df.drop(x,inplace=True)
    df

In [114]:
df = df.drop(194)
df = df.drop(195)
df = df.drop(196)

In [116]:
df = df.drop(191)
df = df.drop(192)
df = df.drop(193)

In [119]:
df.reset_index(drop=True)

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020
0,1,Switzerland,962,84.0,16.5,13.9,"66,933",5,3
1,2,Norway,961,83.2,18.2,13.0,"64,660",6,1
2,3,Iceland,959,82.7,19.2,13.8,"55,782",11,2
3,4,"Hong Kong, China (SAR)",952,85.5,17.3,12.2,"62,607",6,4
4,5,Australia,951,84.5,21.1,12.7,"49,238",18,5
...,...,...,...,...,...,...,...,...,...
186,190,Chad,394,52.5,8.0,2.6,"1,364",7,190
187,191,South Sudan,385,55.0,5.5,5.7,768,1,191
188,NaN,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,Human development groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN